const { createClient } = require('@supabase/supabase-js');
const supabaseUrl = 'https://abc.supabase.co';
const supabaseKey = 'dummy';
const supabase = createClient(supabaseUrl, supabaseKey);

let studentIds = ['a', 'b'];
let notInString = `(${studentIds.map(id => `'${id}'`).join(',')})`;

console.log("NOT IN STRING:", notInString);

// We can just look at the URL generated by the filter
const query = supabase.from('students').delete().eq('class_id', '123').not('id', 'in', notInString);
console.log(query.url.toString());
